name: .NET Core

on:
  push:
    branches: [ development, master ]
  pull_request:
    branches: [ development, master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./src/BFC.sln
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore ${{env.working-directory}}
    - name: Build
      run: dotnet build ${{env.working-directory}} --configuration Release --no-restore
    - name: Test
      run: dotnet test ${{env.working-directory}} --no-restore --verbosity normal
